# Run a DB connectivity test with explicit path so the runner finds the test file reliably.
# Triggers manually (workflow_dispatch) and on push to main so you can re-run after changes.
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  test-db-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show environment and workspace (debug)
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "PWD = $(pwd)"
          echo "List workspace root:"
          ls -la "$GITHUB_WORKSPACE" || true

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements (if any)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run DB connectivity test (explicit path)
        shell: bash
        run: |
          echo "Running db connectivity test from repo root"
          # Use the repo-root relative path explicitly so lookup is deterministic
          python ./test_db_ci.py